# MinGW makefile

include ../src.mk
include ../../../../make/settings/mingw/compiler_cpp.mk

OUT = libpluginscripting.a

# extra include folder
INCLUDES += -I../../../../../build/mingw/$(BUILD_TYPE)/include

include ../../../../make/settings/mingw/build_lib.mk
