# MinGW makefile

include ../src.mk
include ../../../../make/settings/mingw/compiler_cpp.mk

OUT = libafx_types+.a

# additional include folders
INCLUDES += -I../../../afx_types

include ../../../../make/settings/mingw/build_lib.mk
