# MinGW makefile

include ../src.mk
include ../../../../make/settings/mingw/compiler_cpp.mk

OUT = video_source_test.exe

LIBDIR = -L../../../../../build/$(TARGET)/$(BUILD_TYPE)/lib

include ../../../../make/settings/mingw/build_app.mk
